openapi: "3.0.0"
info:
  title: Restful API Service Demo
  description: Some Restful API service demo
  version: 2.0.0
  contact:
    name: Author Me
    email: a@b.c
    url: http://www.myurl

servers:
  - url: /1.0
    description: /1.0

paths:

  /getoptexamples/:
    get:
      tags:
        - Optimization Examples
      summary: get all examples in a list
      description: get all examples in a list
      operationId: app.controllers.api_opt_get_example_list
      responses:
        '200':
          description: The optimization example list
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object

  /runofficialexample/{optId}:
    get:
      tags:
        - Optimization Examples
      summary: run nlopt tutorial example
      description: run nlopt tutorial example
      operationId: app.controllers.api_opt_run_official_example
      parameters:
        - name: optId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: The optimization result from engine
          content:
            application/json:
              schema:
                type: object

  /runlongtimeexample/{optId}:
    get:
      tags:
        - Optimization Examples
      summary: run long time example
      description: run long time example
      operationId: app.controllers.api_opt_run_longtime_example
      parameters:
        - name: optId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: The optimization result from engine
          content:
            application/json:
              schema:
                type: object

  /runlongtimeexamplewithqueue/{optId}:
    get:
      tags:
        - Optimization Examples
      summary: run long time example with sqs queue
      description: run long time example with sqs queue
      operationId: app.controllers.api_opt_run_longtime_example_with_queue
      parameters:
        - name: optId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: The optimization result from engine
          content:
            application/json:
              schema:
                type: object